function C = q2c(q)
% Convert quaternion q to a rotation matrix C (in vector form)
% q is a standard quaternion with the vector part at the start
% C is a 9x1 vector with elements[Column1; Column2; Column3]

x = q(1);
y = q(2);
z = q(3);
s = q(4);

C = [...
    1-2*(y^2  + z^2 );...
      2*(x*y + z*s);...
      2*(x*z - y*s);...
      ...
      2*(y*x - z*s);...
    1-2*(x^2  + z^2 );...
      2*(y*z + x*s);...
      ...
      2*(z*x + y*s);...
      2*(z*y - x*s);...
    1-2*(x^2  + y^2 )];
end

